### ISSUE TITLE
Item-less reputation quests for prediction?

### ISSUE THREAD

**Issue by ShaunaGordon** [fizzwidget/faction-friend#13]
I feel like a broken record with the Saberstalkers stuff, but the weekly quest [Rumble In The Jungle](http://www.wowhead.com/quest=39565/rumble-in-the-jungle) is pretty much solely for reputation. Also, the [Vol'jin's Headhunters dailies](http://www.wowhead.com/faction=1848/voljins-headhunters#quests) are primarily item-less and are a lot of "kill these" and "complete this bonus objective." Unlike the "turn this thing in" repeatable quests, this one is just "go kill these guys," yet they serve the same purpose, and for the Draenor Pathfinder factions, they are literally the only mechanism by which to gain reputation, aside from the Medallion of the Legion.

Does FactionFriend have an existing way to handle these itemless quests? I suspect it would be a good idea to add them in, if possible, as there are several already, and I suspect there are/will be some for Broken Isles Pathfinder, as well as other reputation grinds.

**Comment by fizzwidget** [comment]
I've tried to keep things like daily quests out of FF. This is partly because covering them all would open the floodgates, making a hundred times more things to track in `FFF_ItemInfo`. But it's also because it doesn't quite fit with the way I originally designed the rep bar feature in FF — that feature is mainly about two things:

- Letting you know how much rep gain you "already have" waiting for you based on things you're just sitting on. e.g. You've been running Timewalking dungeons for other stuff, but did you notice you have enough badges to top out one of the old Burning Crusade factions?
- Helping you keep track of your progress when you're farming up mass quantities of faction-turnin items. e.g. One more Dekorhan's Tusk and I can stop getting knocked off this stupid hill.

Both of those are about rep gain you can get *right now*. On the other hand, daily/weekly quests, mob kills, and the like are a different kind of info — they'd be saying that *if* you go and pick up this quest, do some things, and return it (assuming you haven't done so already today/this week), you *could* gain X much faction. While it'd be fun to get something like that into FF someday, it's something better done as a separate feature, not by overloading the rep bar feature. (Also, there are some good offline ways to track that kind of thing, like [WowJuju](https://www.wowjuju.com/repcalc).)
