### ISSUE TITLE
7.2 Paragon Reputations

### ISSUE THREAD

**Issue by Calesta** [fizzwidget/faction-friend#24]
According to the 7.2 release notes,

Several changes for Legion factions that allow earning reputation past Exalted (and towards lucrative rewards!) in WoW patch 7.2:

The “Automatically mark Exalted factions as Inactive” setting no longer inactivates such factions. (If they’re already inactive and you want to track them again, you’ll need to reactivate them yourself.)

Yet every time I earn reputation with a paragon reputation FactionFriend moves it back to the 'Inactive' section.  I'm constantly having to uncheck the 'Move to Inactive' box.

I don't see an option that references paragon reputations specifically.  Is there something I'm missing in terms of options?

**Comment by milotic** [comment]
yep is a bug since 7.2.5 patch

**Comment by fizzwidget** [comment]
Excavating old code and old issues... looks like I made it ignore paragon factions when moving *all* exalted factions inactive, which happens when you first turn on that setting, but didn't check paragon status in the cases where we move one faction at a time inactive automatically (like gaining rep).

Should be fixed in ac0874a for 8.0 release.
